#+title: Studies-in-Algebra-and-Group-Theory - Lecture 3: Group Relations
#+author: S. D. V. Stephens
#+date: 2025-11-30
#+setupfile: ../org-preamble.setup
#+latex_header_extra: \course{Studies-in-Algebra-and-Group-Theory}

#+begin_export latex
\lecture{3}{Group Relations}
#+end_export

We say that two sets have the same */cardinality/* if \(\exists f : X \injto Y\), and we write \(|X| \le |Y|\). This allows us to inter-relate cardinality and function relations via a special theorem.

#+NAME: Schröder-Berstein Theorem
#+BEGIN_thm
If \(\exists f : X \injto Y\) and \(g : X \injto Y\) then \(|X| = |Y|\).
#+END_thm

The Schröder-Berstein theorem provides some immediate results for allowing explicit bijections.

#+NAME: Cardinality of \(\mathbb{N}, \mathbb{Z}, \mathbb{Q}\) to any power
#+BEGIN_prop
Using Schröder-Berstein we can create explicit bijections \(f : \mathbb{Z} \leftrightarrow \mathbb{N}\) given by \(n \mapsto \begin{cases} 2n & \text{if } n \ge 0; \\ -(2n+1) & \text{if } n < 0. \end{cases}\)
#+END_prop

#+NAME: \(|\mathbb{N} \times \mathbb{N}| = |\mathbb{N}| = \mathbb{N}^n\)
#+BEGIN_prop
We create the explicit bijection via \(f : \mathbb{N} \times \mathbb{N} \leftrightarrow \mathbb{N}, \, (k,1) \mapsto 2^k(2l+1)-1\). It follows then that \(\mathbb{N}^a, \mathbb{Z}^b, \mathbb{Q}^c, \forall a,b,c \in \mathbb{N}\).
#+END_prop

#+NAME: Proof
#+BEGIN_prf
Proof of Prop. 3.1.2

Notice that any natural number can be written as \(2^k(m)\) where \(m\) is odd, i.e., \(m = 2n+1\). A bijection is automatically created here with \(2^k(2l+1)\), and the additional \(-1\) at the end of the statement is there to shift the entire bijection down one. So instead of \((0,0) \mapsto 2^0(2(0)+1) = 1\) we get \((0,0) \mapsto 2^0(2(0)+1)-1 = 0\).
#+END_prf

#+NAME: Countable vs uncountable infinites
#+BEGIN_prop
\(|\mathbb{R}| > |\mathbb{N}|\).
#+END_prop

#+NAME: Proof
#+BEGIN_prf
Proof by Cantor

Given by Cantor's diagonal argument, no map \(f : \mathbb{N} \to \mathbb{R}\) be surjective, because:

\[ \begin{cases} f(0) &= a_{00}a_{01}a_{02}a_{03}\ldots \\ f(1) &= a_{10}a_{11}a_{12}a_{13} \ldots \\ f(2) &= a_{20}a_{21}a_{22}a_{23}\ldots \end{cases} \]

then let \(y = b_{0}b_{1}b_{2}b_{3}\) where \(b_j \neq a_{jj}\) for each \(j\). Now look at the \(j^{\text{th}}\) digit, \(y \neq f(j), \, \forall j \in \mathbb{N}\), so \(f\) can't be surjective.
#+END_prf

#+NAME: Cardinality of mappings
#+BEGIN_prop
\(|\mathbb{R}^\mathbb{N}| = |\mathbb{R}|\)
#+END_prop

#+NAME: Proof
#+BEGIN_prf
Proof by Cantor's diagonal used for mappings

We can use the fact that \(|(0,1)| = |\mathbb{R}|\) in addition to Cantor's diagonal argument as a decimal expansion---\(t = 0.t_{1}t_{2}t_{3}\ldots\)---with \(t_i\) as an integer between \(0\) and \(9\). So now to show \(\exists f \mid f : (0,1) \leftrightarrow (0,1)^{\mathbb{N}}\), we create some \(s_j \in (0,1)^{\mathbb{N}}\) and construct the bijection via:

\[\begin{cases}s_{1} &= 0.t_{1}t_{3}t_{5}\ldots \\ s_{2} &= 0.t_{2}t_{6}t_{10}\ldots \\ s_{3} &= 0.t_{4}t_{12}t_{20}\ldots
\end{cases}\]

We say that \(s_1\) is made up of all \(t_i\) that are odd; \(s_{2}\) is made up of all \(i\) which are odd such that \(i \cdot 2 \forall i \in s_{2}\); \(s_3\) is made up of all \(i\) which are odd such that \(i \cdot 2^2, \forall i \in s_{3}\), \(i \cdot 2^3 \in s_3\) and so on (the general form being \(i \cdot 2^n \mid n = j-1\)). Therefore there exists a bijection between \((0,1) \leftrightarrow (0,1)^{\mathbb{N}}\).
#+END_prf

#+NAME: There does not exist a largest cardinality
#+BEGIN_prop
Let \(\mcP(S)\) be the standard powerset. It follows then that \(\mcP(S) = \{0,1\}^S\) and \(|\mcP(S)| > |S|\) for any \(S\).
#+END_prop

#+NAME: Proof
#+BEGIN_prf
Proof of non-existence of largest cardinality

Recall that \(\{0,1\}^S = \{ \text{all } f \text{ such that } f : S \to \{0,1\} \}\). There must exist a bijection since \(|\mcP(S)| = 2^{|S|}\) and \(|\{0,1\}^S| = 2^{|S|}\). Now to show \(|\mcP(S)| > |S|\) we use proof by contradiction: suppose \(\exists \alpha : S \leftrightarrow \mcP(S)\) and let \(A \subset S\) defined by \(A \coloneqq \{s \in S \mid s \neq \alpha(s)\}\), now for \(A = \alpha(t)\) for some \(t \in A\) we notice that \(t \not\in \alpha(t) = A\) means that \(t \in A\), but to say \(t \in \alpha(t) \implies t \not\in A\), thus we have a contradiction.
#+END_prf

Another option for this proof, though less formal, can be found by showing that \(\mcP(S) = \{0,1\}^S\) and that subsets of \(S\) have \(f\) such that \(f \mapsto f^{-1}\); let \(A \subset S\) then

\[
A \mapsto \left(\mathbb{1}_A : x \mapsto \begin{cases}
  1 & \text{if } x \in A \\
  0 & \text{if } x \not\in A
\end{cases}\right)
\]

Note that if \(S\) is finite then \(|S| = n\) and \(\mcP(S) = 2^n\). This naturally leads us into our next theorem regarding the infinitude of the cardinality of \(S\) in relation to \(\mcP(S)\).

* Quotient groups

Consider \(\mathbb{Z} / n\). Under the equivalence relation congruence mod \(n\) we can take the sum of the various subsets that mod \(n\) partitions \(\mathbb{Z}\) into as the law of composition given by \((a + n\mathbb{Z}) + (b + n\mathbb{Z}) = a + b + n\mathbb{Z}\). Notice that we can let \(T\) be the set of equivalence classes under mod \(n\), and thus we have a homomorphic map from \(\mathbb{Z} \to T\). Finally, \(T = \mathbb{Z} / n\).

Why stop at integers? What if we want to make congruence mod \(H\) where is a subgroup \(H \subset G\)? Under what cases, given that we /can/ make mod \(H\) equivalence classes (we will define this in a bit) is the quotient map \(G \to T\) a homomorphism?


** Congruence mod \(H\)

For any two elements \(a, b \in G\) we define \(a \sim b \iff ab^{-1} \in H\), this is to say that \(a \in bH\). We thus have a \(a \sim a\) since \(e \in H\), \(a \sim b \implies ab^{-1} \in H\), and \(ba^{-1} = (ab^{-1})^{-1} \in H\), thus \(b \sim a\). Finally, \(a \sim b, b \sim c\) meaning that \(ab^{-1}\) and \(bc^{-1}\)

* Symmetry group

* More group relations

** Kernels, images, and order

#+NAME: Kernel
#+BEGIN_dfn
The */kernel/* of a group homomorphism, \(\varphi : G \to H\), is given by \(\ker(\varphi) = \{a \in G \mid \varphi(a) = e_H\}\).
#+END_dfn

#+BEGIN_prop
The kernel is a subgroup of \(G\) and \(\varphi\) is injective \(\iff \ker(\varphi) = \{e_G\}\) (\(\varphi(a) = \varphi(b) \iff a^{-1}b \in \ker(\varphi)\)).
#+END_prop

#+NAME: Image of group homomorphisms
#+BEGIN_dfn
The image of a group homomorphism \(\varphi : G \to H\) is \(\Img(\varphi) = \varphi(G) = \{b \in H \mid \exists a \in G : \varphi(a) = b\}\). This is a subgroup of \(H\) and \(\varphi\) is surjective \(\iff \Img(\varphi) = H\).
#+END_dfn

#+BEGIN_note
If \(\varphi\) is injective, then \(G\) is isomorphic to the subgroup \(\Img(\varphi) \subset H\). (if the isom. is given by the map \(G \to \Img(\varphi), \, a \mapsto \varphi(a)\)).
#+END_note

** Finite symmetric groups
